//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr7
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_history
    {
        public int id { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> broken_part_id { get; set; }
        public Nullable<decimal> repair_cost { get; set; }
        public string status { get; set; }
    
        public virtual parts parts { get; set; }
    }
}
