//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr7
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_stats
    {
        public int id { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<int> day_count { get; set; }
    }
}
