//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr7
{
    using System;
    using System.Collections.Generic;
    
    public partial class suplly_orders
    {
        public int id { get; set; }
        public Nullable<int> part_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> delivery_delay { get; set; }
    
        public virtual parts parts { get; set; }
    }
}
